export const UPDATE_CELL = "UPDATE_CELL";
export const SELECT_CELL = "SELECT_CELL";
export const SELECT_TO_CELL = "SELECT_TO_CELL";
export const UPDATE_ALL_SELECTED_CELLS = "UPDATE_ALL_SELECTED_CELLS";